In [5]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [3]:
from word2number import w2n

In [31]:
df=pd.read_csv('hiring.csv')

In [32]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [33]:
med=df['test_score(out of 10)'].median()
df['test_score(out of 10)'].fillna(med,inplace=True)
df['experience'].fillna('zero',inplace=True)

In [35]:
df['experience']=df['experience'].apply(w2n.word_to_num)

In [36]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [41]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [39]:
reg=linear_model.LinearRegression()

In [43]:
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']],df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [44]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [47]:
reg.intercept_

17737.26346433771

In [49]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [50]:
reg.predict([[12,10,10]])

array([92002.18340611])